### ISSUE TITLE
Adicionar OTS

### ISSUE THREAD

**Issue by jonatasbaldin** [manualdousuario/pcdomanual-site#1]
Acabamos de instalar mais um serviço no PC, o [OTS](https://segredo.pcdomanual.com).

Precisamos colocar esse serviço no site com descrição, link, documentação etc.

**Comment by rghedin** [comment]
Apenas para registro: o OTS (e qualquer serviço similar) foi descontinuado na migração para a nuvem da Oracle.

Fechando aqui.
